"""
orchestrator_v2_vlm.py
----------------------
Real-VLM version of orchestrator_v2.py.

Same observation trajectory and same gate logic, but candidate clarification
questions are *generated by Qwen2.5-VL at decision time* instead of being
hard-coded.

Use this when you want to run the closer-to-final pipeline. For fast
debugging keep using orchestrator_v2.py (mock questions, ~1 second).

How it differs from the mock orchestrator:
  - Uses recipe_terms.json (30 real recipes) instead of test_recipe_terms.json
  - Loads static recipe graphs from recipe_graphs/instruct/
  - Only calls the VLM when the *cheap* gate (budget + entropy) says it's
    worth it — saves a ~30 s model load if entropy is already low
  - Trims the prompt to only "active" recipes (above a small probability
    floor) so the prompt doesn't blow past Qwen's context window
  - Robustly parses the VLM's JSON output (strips code fences, validates
    fields, drops malformed entries)

Run:
    PYTORCH_ENABLE_MPS_FALLBACK=1 python orchestrator_v2_vlm.py
"""

from __future__ import annotations

import json
import re

from belief_updater_v2 import BeliefUpdaterV2
from questioning_pipeline import (
    load_static_graphs,
    build_question_prompt,
    run_qwen_prompt,
)
from questioning_planner import should_ask


# ─────────────────────────────────────────────────────────────────────────
# Mock observation trajectory (same as orchestrator_v2.py).
# In production this is replaced by per-window VLM observations from
# run_dynamic_loop.py, fed into bu.update() one window at a time.
# ─────────────────────────────────────────────────────────────────────────

WINDOWS = [
    {"window": 1,
     "ingredients": ["cucumber"],
     "actions":     ["slice"]},
    {"window": 2,
     "ingredients": ["cucumber", "onion"],
     "actions":     ["slice", "chop"]},
    {"window": 3,
     "ingredients": ["cucumber", "onion", "sour cream",
                     "white sugar", "white vinegar"],
     "actions":     ["slice", "chop", "whisk"]},
    {"window": 4,
     "ingredients": ["cucumber", "onion", "sour cream",
                     "white sugar", "white vinegar"],
     "actions":     ["slice", "chop", "whisk", "toss", "cover", "refrigerate"]},
]

# ─────────────────────────────────────────────────────────────────────────
# Question-conditional human answers
#
# The cook in this demo is making a *creamy cucumber salad* — they've
# sliced cucumber, chopped onion, and are about to whisk sour cream into
# the dressing. pick_human_answer() picks a plausible answer based on what
# the question is actually asking about, so that:
#   - tool questions get an honest "knife" answer (uninformative → IG_Q ≈ 0)
#   - dressing/ingredient questions get the "sour cream" answer (high IG_Q)
# This lets predicted EIG and realised IG_Q be meaningfully compared.
# Swap with a real human input loop for live sessions.
# ─────────────────────────────────────────────────────────────────────────

DEFAULT_HUMAN_ANSWER = "I am adding sour cream to make a creamy dressing"


def pick_human_answer(question_text: str) -> str:
    """Route the human's answer by question keywords. First match wins."""
    q = question_text.lower()

    # Tool / utensil question — honest but uninformative
    if any(w in q for w in ["tool", "knife", "utensil", "what are you using"]):
        return "I am using a knife and a cutting board"

    # First step / what was done — already-observed actions
    if "first" in q or "started" in q or "began" in q:
        return "I started by slicing the cucumber"

    # Next step / next action — what's coming
    if "next" in q and any(w in q for w in ["step", "action", "doing", "perform"]):
        return "I am about to whisk sour cream into the dressing"

    # Stage question
    if "stage" in q:
        return "I am at the dressing stage, adding sour cream"

    # Herb / spice question — answer depends on which herb the cook uses;
    # here we use no herb in particular (cook didn't mention one)
    if "herb" in q or "spice" in q:
        return "I am not using any herb in this dressing"

    # Dressing / ingredient question — the informative answer
    if "dressing" in q or "sauce" in q:
        return "I am whisking sour cream into a creamy dressing"
    if "ingredient" in q:
        return "I am adding sour cream to the dressing"

    return DEFAULT_HUMAN_ANSWER


# Hyperparameters — same defaults as the mock orchestrator.
ENTROPY_THRESHOLD = 0.5      # bits; below this, belief is "sharp enough"
EIG_THRESHOLD = 0.10         # bits; below this, no question is worth asking
# MAX_QUESTIONS = 2          # budget per session — DISABLED for now
MAX_QUESTIONS = 9_999        # effectively unlimited (re-enable budget by
                             # restoring the 2 above)

# How many recipes to keep in the VLM prompt. Trimming to active recipes
# keeps the prompt short and helps Qwen focus on the actual ambiguity.
ACTIVE_RECIPE_THRESHOLD = 0.02

# Paths to the real (non-mock) artefacts.
RECIPE_TERMS_PATH = "recipe_terms.json"
GRAPH_FOLDER = "recipe_graphs/instruct"


# ─────────────────────────────────────────────────────────────────────────
# VLM input prep
# ─────────────────────────────────────────────────────────────────────────

def _graph_name(graph: dict) -> str:
    """Mirror the cleaning rule used by recipe_vectoriser.py."""
    return graph.get("name", "").replace("_", " ").strip()


def trim_to_active_recipes(
    belief: dict[str, float],
    static_graphs: list[dict],
    threshold: float = ACTIVE_RECIPE_THRESHOLD,
) -> tuple[dict[str, float], list[dict]]:
    """
    Drop recipes whose probability is below `threshold` from both the belief
    snapshot and the static graph list. Keeps the VLM prompt focused on
    recipes that are actually plausible right now.
    """
    active_names = {name for name, p in belief.items() if p >= threshold}
    if not active_names:                       # safety net — keep top-5
        active_names = set(
            sorted(belief, key=belief.get, reverse=True)[:5]
        )
    trimmed_belief = {
        name: round(p, 4) for name, p in belief.items() if name in active_names
    }
    trimmed_graphs = [
        g for g in static_graphs if _graph_name(g) in active_names
    ]
    return trimmed_belief, trimmed_graphs


# ─────────────────────────────────────────────────────────────────────────
# VLM output parsing
# ─────────────────────────────────────────────────────────────────────────

_FENCE_RE = re.compile(r"^```(?:json)?\s*|\s*```$", re.MULTILINE)


def parse_vlm_questions(raw_response: str) -> list[dict]:
    """
    Parse Qwen's JSON output into the dict shape that the planner expects.

    Tolerates:
      - markdown code fences (```json ... ```)
      - leading or trailing commentary outside the JSON object
      - missing or wrongly-typed fields (best-effort fallback)

    Returns a list of {rank, question, question_form, targets, distinguishes}
    dicts. Malformed entries are silently dropped.
    """
    text = _FENCE_RE.sub("", raw_response).strip()

    # Find the outermost {...} block; this is robust to "Here is the JSON:" preambles.
    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end == -1 or end < start:
        print("  [parse] No JSON object found in VLM response.")
        return []

    try:
        parsed = json.loads(text[start : end + 1])
    except json.JSONDecodeError as e:
        print(f"  [parse] JSON decode failed: {e}")
        return []

    raw_questions = parsed.get("questions", [])
    if not isinstance(raw_questions, list):
        print("  [parse] 'questions' field is missing or not a list.")
        return []

    clean: list[dict] = []
    for i, q in enumerate(raw_questions):
        if not isinstance(q, dict):
            continue
        question_text = (q.get("question") or "").strip()
        if not question_text:
            continue
        targets = q.get("targets", [])
        distinguishes = q.get("distinguishes", [])
        clean.append({
            "rank":         q.get("rank", i + 1),
            "question":     question_text,
            "question_form": q.get("question_form", "wh"),
            "targets":      targets if isinstance(targets, list) else [],
            "distinguishes": distinguishes if isinstance(distinguishes, list) else [],
        })
    return clean


def generate_vlm_questions(
    belief_updater: BeliefUpdaterV2,
    static_graphs: list[dict],
) -> list[dict]:
    """
    Run the full VLM question generation step:
      1. Trim belief + graphs to active recipes
      2. Build the prompt via questioning_pipeline.build_question_prompt
      3. Call Qwen via questioning_pipeline.run_qwen_prompt
      4. Parse the response into the planner's dict format
    """
    trimmed_belief, trimmed_graphs = trim_to_active_recipes(
        belief_updater.belief, static_graphs
    )
    print(f"  [VLM] Active recipes in prompt: {len(trimmed_belief)}")

    prompt = build_question_prompt(trimmed_graphs, trimmed_belief)
    print("  [VLM] Calling Qwen (this loads the model on first call)...")
    raw_response = run_qwen_prompt(prompt)

    print("\n  [VLM raw response]")
    print("  " + raw_response.replace("\n", "\n  "))

    questions = parse_vlm_questions(raw_response)
    print(f"\n  [VLM] Parsed {len(questions)} candidate question(s).")
    return questions


# ─────────────────────────────────────────────────────────────────────────
# Main loop
# ─────────────────────────────────────────────────────────────────────────

def main():
    bu = BeliefUpdaterV2(recipe_terms_path=RECIPE_TERMS_PATH)

    # Static graphs are loaded lazily on the first VLM call (saves time if
    # we never end up asking).
    static_graphs: list[dict] | None = None

    questions_asked = 0
    print(f"\nMax entropy: {bu.max_entropy():.3f} bits")

    for w in WINDOWS:
        print(f"\n── Window {w['window']} ──────────────────────────────────")

        # 1. Observation update
        bu.update(ingredients_seen=w["ingredients"], actions_seen=w["actions"])
        top, p = bu.top_recipe()
        print(f"  entropy : {bu.entropy():.4f} bits")
        print(f"  top     : {top} ({p:.3f})")

        # 2. CHEAP gate first — avoids the 30 s VLM load when the answer is
        # already obvious. Budget gate is disabled for now (re-enable by
        # uncommenting the block below).
        # if questions_asked >= MAX_QUESTIONS:
        #     print("  [gate] Question budget exhausted — skipping.")
        #     continue
        if bu.entropy() < ENTROPY_THRESHOLD:
            print("  [gate] Belief is sharp enough — skipping.")
            continue

        # 3. EXPENSIVE step — generate candidate questions with the VLM.
        if static_graphs is None:
            print("  [setup] Loading static recipe graphs...")
            static_graphs = load_static_graphs(GRAPH_FOLDER)

        questions = generate_vlm_questions(bu, static_graphs)
        if not questions:
            print("  [gate] No usable questions from VLM — skipping.")
            continue

        # 4. Score with the planner. We pass entropy_threshold=0.0 here
        # because we already vetted entropy above; this call only enforces
        # the EIG threshold and the budget.
        ask, best_q, ranked = should_ask(
            belief_updater=bu,
            questions=questions,
            entropy_threshold=0.0,
            eig_threshold=EIG_THRESHOLD,
            questions_asked=questions_asked,
            max_questions=MAX_QUESTIONS,
        )

        print("\n  candidate EIGs:")
        for q in ranked:
            print(f"    [{q['measured_eig']:.3f}]  {q['question']}")

        if not ask:
            print("  [gate] Best EIG below threshold — skipping.")
            continue

        # 5. Fire the chosen question. Route the demo's hard-coded human
        # answer based on what was actually asked, so the predicted EIG and
        # realised IG_Q are meaningfully comparable.
        answer = pick_human_answer(best_q["question"])

        print(f"\n  >> Asking: {best_q['question']}")
        print(f"     human    : {answer}")
        print(f"     predicted EIG : {best_q['measured_eig']:.4f} bits")

        h_before = bu.entropy()
        bu.incorporate_answer(answer)
        h_after = bu.entropy()
        realised = h_before - h_after

        print(f"     realised IG_Q : {realised:.4f} bits "
              f"(Δ vs predicted: {realised - best_q['measured_eig']:+.4f})")
        questions_asked += 1

    # Final report
    top, p = bu.top_recipe()
    print("\n" + "═" * 60)
    print(f"Final prediction : {top} ({p:.4f})")
    print(f"Final entropy    : {bu.entropy():.4f} bits")
    print(f"Questions asked  : {questions_asked}")
    print(f"IG_Q history     : {json.dumps(bu.ig_q_history(), indent=2)}")


if __name__ == "__main__":
    main()
