"""
orchestrator_v2_vlm.py
----------------------
Real-VLM version of orchestrator_v2.py.

Same observation trajectory and same gate logic, but candidate clarification
questions are *generated by Qwen2.5-VL at decision time* instead of being
hard-coded.

Use this when you want to run the closer-to-final pipeline. For fast
debugging keep using orchestrator_v2.py (mock questions, ~1 second).

How it differs from the mock orchestrator:
  - Uses recipe_terms.json (30 real recipes) instead of test_recipe_terms.json
  - Loads static recipe graphs from recipe_graphs/instruct/
  - Only calls the VLM when the *cheap* gate (budget + entropy) says it's
    worth it — saves a ~30 s model load if entropy is already low
  - Trims the prompt to only "active" recipes (above a small probability
    floor) so the prompt doesn't blow past Qwen's context window
  - Robustly parses the VLM's JSON output (strips code fences, validates
    fields, drops malformed entries)

Run:
    PYTORCH_ENABLE_MPS_FALLBACK=1 python orchestrator_v2_vlm.py
"""

from __future__ import annotations

import json
import re

from belief_updater_v2 import BeliefUpdaterV2
from questioning_pipeline import (
    build_recipe_context,
    build_question_prompt,
    run_qwen_prompt,
)
from questioning_planner import should_ask


# ─────────────────────────────────────────────────────────────────────────
# Mock observation trajectory (same as orchestrator_v2.py).
# In production this is replaced by per-window VLM observations from
# run_dynamic_loop.py, fed into bu.update() one window at a time.
# ─────────────────────────────────────────────────────────────────────────

WINDOWS = [
    {"window": 1,
     "ingredients": ["cucumber"],
     "actions":     ["slice"]},
    {"window": 2,
     "ingredients": ["cucumber", "onion"],
     "actions":     ["slice", "chop"]},
    {"window": 3,
     "ingredients": ["cucumber", "onion", "sour cream",
                     "white sugar", "white vinegar"],
     "actions":     ["slice", "chop", "whisk"]},
    {"window": 4,
     "ingredients": ["cucumber", "onion", "sour cream",
                     "white sugar", "white vinegar"],
     "actions":     ["slice", "chop", "whisk", "toss", "cover", "refrigerate"]},
]

# ─────────────────────────────────────────────────────────────────────────
# Question-conditional human answers
#
# The cook in this demo is making a *creamy cucumber salad* — they've
# sliced cucumber, chopped onion, and are about to whisk sour cream into
# the dressing. pick_human_answer() picks a plausible answer based on what
# the question is actually asking about, so that:
#   - tool questions get an honest "knife" answer (uninformative → IG_Q ≈ 0)
#   - dressing/ingredient questions get the "sour cream" answer (high IG_Q)
# This lets predicted EIG and realised IG_Q be meaningfully compared.
# Swap with a real human input loop for live sessions.
# ─────────────────────────────────────────────────────────────────────────

DEFAULT_HUMAN_ANSWER = "I am adding sour cream to make a creamy dressing"


def pick_human_answer(question_text: str) -> str:
    """Route the human's answer by question keywords. First match wins."""
    q = question_text.lower()

    # Tool / utensil question — honest but uninformative
    if any(w in q for w in ["tool", "knife", "utensil", "what are you using"]):
        return "I am using a knife and a cutting board"

    # First step / what was done — already-observed actions
    if "first" in q or "started" in q or "began" in q:
        return "I started by slicing the cucumber"

    # Next step / next action — what's coming
    if "next" in q and any(w in q for w in ["step", "action", "doing", "perform"]):
        return "I am about to whisk sour cream into the dressing"

    # Stage question
    if "stage" in q:
        return "I am at the dressing stage, adding sour cream"

    # Herb / spice question — answer depends on which herb the cook uses;
    # here we use no herb in particular (cook didn't mention one)
    if "herb" in q or "spice" in q:
        return "I am not using any herb in this dressing"

    # Dressing / ingredient question — the informative answer
    if "dressing" in q or "sauce" in q:
        return "I am whisking sour cream into a creamy dressing"
    if "ingredient" in q:
        return "I am adding sour cream to the dressing"

    return DEFAULT_HUMAN_ANSWER


# Hyperparameters — same defaults as the mock orchestrator.
ENTROPY_THRESHOLD = 0.5      # bits; below this, belief is "sharp enough"
EIG_THRESHOLD = 0.10         # bits; below this, no question is worth asking
# MAX_QUESTIONS = 2          # budget per session — DISABLED for now
MAX_QUESTIONS = 9_999        # effectively unlimited (re-enable budget by
                             # restoring the 2 above)

# Negation handling — see is_negative_answer() and apply_negation_update()
# below. When the human answers with a "no" / "not" / "without" sentence,
# we skip the embedding pipeline (which cannot represent negation) and apply
# a direct multiplicative penalty to recipes whose vocabulary contains the
# question's targets.
NEGATION_PENALTY = 0.10      # multiplier applied to "denied" recipes


# ─────────────────────────────────────────────────────────────────────────
# Negation handling
# ─────────────────────────────────────────────────────────────────────────

# Triggers we treat as "this answer is a denial of the question's targets".
# Word-boundary matches (we pad the answer with spaces before checking).
NEGATION_TRIGGERS = (
    " not ", " no ", " none ", " without ", " neither ",
    " don't ", " doesn't ", " didn't ", " isn't ", " aren't ", " won't ",
)


def is_negative_answer(answer_text: str) -> bool:
    """Cheap heuristic: does this answer deny rather than affirm?"""
    padded = " " + answer_text.lower().strip() + " "
    return any(trigger in padded for trigger in NEGATION_TRIGGERS)


def apply_negation_update(
    bu: BeliefUpdaterV2,
    targets: list[str],
    penalty: float = NEGATION_PENALTY,
) -> tuple[float, float]:
    """
    Direct Bayesian down-weight for "no" answers.

    The question proposed `targets` as candidate answers. The human said
    none of them apply. Therefore recipes whose vocabulary contains any of
    those targets are less likely. We multiply their belief by `penalty`,
    then renormalise.

    We do this DIRECTLY instead of routing through incorporate_answer,
    because the sentence-embedding pipeline cannot distinguish
    "I am using sour cream" from "I am NOT using sour cream" — both
    vectors are *about* sour cream and would both pull the belief in the
    same direction. The direct multiplicative update encodes the negation
    correctly.

    Returns (h_before, h_after) so the caller can log IG_Q.
    """
    h_before = bu.entropy()

    targets_l = [t.lower().strip() for t in targets if t.strip()]
    if not targets_l:
        return h_before, h_before    # nothing to negate

    matched_recipes: list[str] = []
    for name, rec_terms in bu.recipe_term_vectors.items():
        contains_any = False
        for target in targets_l:
            for term in rec_terms:
                tl = term.lower()
                if target in tl or tl in target:
                    contains_any = True
                    break
            if contains_any:
                break
        if contains_any:
            bu.belief[name] *= penalty
            matched_recipes.append(name)

    # Renormalise
    total = sum(bu.belief.values())
    if total > 0:
        bu.belief = {k: v / total for k, v in bu.belief.items()}
    else:
        bu.belief = {k: 1.0 / bu.N for k in bu.recipe_names}

    bu.history.append(dict(bu.belief))
    h_after = bu.entropy()

    print(f"     [negation] down-weighted {len(matched_recipes)} recipe(s) "
          f"containing any of {targets_l}:")
    for name in matched_recipes[:8]:
        print(f"        - {name}")
    if len(matched_recipes) > 8:
        print(f"        ... and {len(matched_recipes) - 8} more")

    return h_before, h_after

# How many recipe candidates the VLM sees in the prompt. Tunes the trade-off
# between focus (smaller k → sharper prompt) and coverage (larger k → may
# distinguish more recipes).
PROMPT_TOP_K = 8
PROMPT_ACTIVE_THRESHOLD = 0.02

# Path to the V2 vector store. Static recipe graphs are no longer loaded —
# the canonical recipe representation is the per-term vocabulary inside
# BeliefUpdaterV2 itself, surfaced via build_recipe_context().
RECIPE_TERMS_PATH = "recipe_terms.json"


# ─────────────────────────────────────────────────────────────────────────
# VLM output parsing
# ─────────────────────────────────────────────────────────────────────────

_FENCE_RE = re.compile(r"^```(?:json)?\s*|\s*```$", re.MULTILINE)


def parse_vlm_questions(raw_response: str) -> list[dict]:
    """
    Parse Qwen's JSON output into the dict shape that the planner expects.

    Tolerates:
      - markdown code fences (```json ... ```)
      - leading or trailing commentary outside the JSON object
      - missing or wrongly-typed fields (best-effort fallback)

    Returns a list of {rank, question, question_form, targets, distinguishes}
    dicts. Malformed entries are silently dropped.
    """
    text = _FENCE_RE.sub("", raw_response).strip()

    # Find the outermost {...} block; this is robust to "Here is the JSON:" preambles.
    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end == -1 or end < start:
        print("  [parse] No JSON object found in VLM response.")
        return []

    try:
        parsed = json.loads(text[start : end + 1])
    except json.JSONDecodeError as e:
        print(f"  [parse] JSON decode failed: {e}")
        return []

    raw_questions = parsed.get("questions", [])
    if not isinstance(raw_questions, list):
        print("  [parse] 'questions' field is missing or not a list.")
        return []

    clean: list[dict] = []
    for i, q in enumerate(raw_questions):
        if not isinstance(q, dict):
            continue
        question_text = (q.get("question") or "").strip()
        if not question_text:
            continue
        targets = q.get("targets", [])
        distinguishes = q.get("distinguishes", [])
        clean.append({
            "rank":         q.get("rank", i + 1),
            "question":     question_text,
            "question_form": q.get("question_form", "wh"),
            "targets":      targets if isinstance(targets, list) else [],
            "distinguishes": distinguishes if isinstance(distinguishes, list) else [],
        })
    return clean


def generate_vlm_questions(belief_updater: BeliefUpdaterV2) -> list[dict]:
    """
    Run the full VLM question generation step:
      1. Build the recipe context (observed terms + active recipes with
         remaining vocabulary + flat vocabulary pool) directly from the
         BeliefUpdaterV2 state — no static graph JSONs involved.
      2. Build the prompt via questioning_pipeline.build_question_prompt
      3. Call Qwen via questioning_pipeline.run_qwen_prompt
      4. Parse the response into the planner's dict format
    """
    context = build_recipe_context(
        belief_updater,
        active_threshold=PROMPT_ACTIVE_THRESHOLD,
        top_k=PROMPT_TOP_K,
    )
    n_active = sum(1 for p in belief_updater.belief.values()
                   if p >= PROMPT_ACTIVE_THRESHOLD)
    print(f"  [VLM] Active recipes in context: {min(n_active, PROMPT_TOP_K)}")

    prompt = build_question_prompt(recipe_context=context)
    print("  [VLM] Calling Qwen (this loads the model on first call)...")
    raw_response = run_qwen_prompt(prompt)

    print("\n  [VLM raw response]")
    print("  " + raw_response.replace("\n", "\n  "))

    questions = parse_vlm_questions(raw_response)
    print(f"\n  [VLM] Parsed {len(questions)} candidate question(s).")
    return questions


# ─────────────────────────────────────────────────────────────────────────
# Main loop
# ─────────────────────────────────────────────────────────────────────────

def _norm(text: str) -> str:
    """Normalise a question string for dedup comparison."""
    return " ".join(text.lower().split()).rstrip("?.! ")


def main():
    bu = BeliefUpdaterV2(recipe_terms_path=RECIPE_TERMS_PATH)

    questions_asked = 0
    asked_question_texts: set[str] = set()    # track questions already used
    print(f"\nMax entropy: {bu.max_entropy():.3f} bits")

    for w in WINDOWS:
        print(f"\n── Window {w['window']} ──────────────────────────────────")

        # 1. Observation update
        bu.update(ingredients_seen=w["ingredients"], actions_seen=w["actions"])
        top, p = bu.top_recipe()
        print(f"  entropy : {bu.entropy():.4f} bits")
        print(f"  top     : {top} ({p:.3f})")

        # 2. CHEAP gate first — avoids the 30 s VLM load when the answer is
        # already obvious. Budget gate is disabled for now (re-enable by
        # uncommenting the block below).
        # if questions_asked >= MAX_QUESTIONS:
        #     print("  [gate] Question budget exhausted — skipping.")
        #     continue
        if bu.entropy() < ENTROPY_THRESHOLD:
            print("  [gate] Belief is sharp enough — skipping.")
            continue

        # 3. EXPENSIVE step — generate candidate questions with the VLM,
        # passing it the V2-native context (active recipes + remaining
        # vocabulary) instead of raw static graphs.
        questions = generate_vlm_questions(bu)
        if not questions:
            print("  [gate] No usable questions from VLM — skipping.")
            continue

        # Repeat-question filter is DISABLED for now (it felt too hard-coded).
        # If you want it back, uncomment the block below and remove the
        # `fresh_questions = questions` line.
        #
        # fresh_questions = [
        #     q for q in questions
        #     if _norm(q["question"]) not in asked_question_texts
        # ]
        # n_dropped = len(questions) - len(fresh_questions)
        # if n_dropped:
        #     print(f"  [filter] Dropped {n_dropped} repeat question(s).")
        # if not fresh_questions:
        #     print("  [gate] All VLM questions are repeats — skipping.")
        #     continue
        fresh_questions = questions

        # 4. Score with the planner. We pass entropy_threshold=0.0 here
        # because we already vetted entropy above; this call only enforces
        # the EIG threshold and the budget.
        ask, best_q, ranked = should_ask(
            belief_updater=bu,
            questions=fresh_questions,
            entropy_threshold=0.0,
            eig_threshold=EIG_THRESHOLD,
            questions_asked=questions_asked,
            max_questions=MAX_QUESTIONS,
        )

        # Per-branch EIG breakdown — for each candidate question, show what
        # each top-k recipe is hypothesised to answer and how much entropy
        # would drop in that branch. This makes the selection transparent.
        print("\n  candidate questions (with EIG breakdown):")
        for q in ranked:
            print(f"    [{q['measured_eig']:.3f} bits]  {q['question']}")
            for b in q["branches"]:
                if b["answer"] is None:
                    print(f"        ↳ {b['recipe']:<35} (p={b['p']:.3f})  "
                          f"no useful sim answer")
                    continue
                contribution = b["p"] * b["delta_h"]
                print(f"        ↳ {b['recipe']:<35} (p={b['p']:.3f})  "
                      f"sim → {b['answer']!r:<25}  "
                      f"ΔH={b['delta_h']:+.3f}  contrib={contribution:+.3f}")

        if not ask:
            print("  [gate] Best EIG below threshold — skipping.")
            continue

        # 5. Fire the chosen question. Route the demo's hard-coded human
        # answer based on what was actually asked, so the predicted EIG and
        # realised IG_Q are meaningfully comparable.
        answer = pick_human_answer(best_q["question"])

        print(f"\n  >> Asking: {best_q['question']}")
        print(f"     human    : {answer}")
        print(f"     predicted EIG : {best_q['measured_eig']:.4f} bits")

        # Negation answers go through the direct down-weight, NOT through
        # the embedding pipeline (which can't represent "not").
        if is_negative_answer(answer):
            h_before, h_after = apply_negation_update(
                bu,
                targets=best_q.get("targets", []),
                penalty=NEGATION_PENALTY,
            )
            # Log to ig_q_history so it appears in the final summary
            bu._ig_q_history.append({
                "answer": answer,
                "extracted_terms": [],
                "negation_targets": best_q.get("targets", []),
                "entropy_before": round(h_before, 4),
                "entropy_after": round(h_after, 4),
                "ig_q": round(h_before - h_after, 4),
            })
        else:
            h_before = bu.entropy()
            bu.incorporate_answer(answer)
            h_after = bu.entropy()
        realised = h_before - h_after

        print(f"     realised IG_Q : {realised:.4f} bits "
              f"(Δ vs predicted: {realised - best_q['measured_eig']:+.4f})")
        questions_asked += 1
        # asked_question_texts.add(_norm(best_q["question"]))  # filter disabled

    # Final report
    top, p = bu.top_recipe()
    print("\n" + "═" * 60)
    print(f"Final prediction : {top} ({p:.4f})")
    print(f"Final entropy    : {bu.entropy():.4f} bits")
    print(f"Questions asked  : {questions_asked}")
    print(f"IG_Q history     : {json.dumps(bu.ig_q_history(), indent=2)}")


if __name__ == "__main__":
    main()
